# Generated by Django 5.2 on 2025-04-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostManager',
        ),
    ]
